// Custom behaviors module — generated by the Immersio Editor engine customizer.
// This file is overwritten by AI when engine instructions are applied.

export function init(engine) {}
export function update(engine, dt) {}
