export const InputActions = {
  MOVE_X: 'MOVE_X',
  MOVE_Y: 'MOVE_Y',
  TURN_X: 'TURN_X',
  TRIGGER_LEFT: 'TRIGGER_LEFT',
  TRIGGER_RIGHT: 'TRIGGER_RIGHT',
  GRIP_LEFT: 'GRIP_LEFT',
  GRIP_RIGHT: 'GRIP_RIGHT',
  TRIGGER_LEFT_DOWN: 'TRIGGER_LEFT_DOWN',
  TRIGGER_RIGHT_DOWN: 'TRIGGER_RIGHT_DOWN',
  GRIP_LEFT_DOWN: 'GRIP_LEFT_DOWN',
  GRIP_RIGHT_DOWN: 'GRIP_RIGHT_DOWN',
  TRIGGER_LEFT_UP: 'TRIGGER_LEFT_UP',
  TRIGGER_RIGHT_UP: 'TRIGGER_RIGHT_UP',
  GRIP_LEFT_UP: 'GRIP_LEFT_UP',
  GRIP_RIGHT_UP: 'GRIP_RIGHT_UP',
  B_RIGHT_DOWN: 'B_RIGHT_DOWN',
  B_RIGHT_UP: 'B_RIGHT_UP',
  A_RIGHT_DOWN: 'A_RIGHT_DOWN',
  A_RIGHT_UP: 'A_RIGHT_UP',
};

export const DEADZONE_STICK = 0.15;
export const DEADZONE_SNAP = 0.6;
