#!/usr/bin/env node

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawn } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../..');

const args = process.argv.slice(2);

if (args.length < 2) {
  console.error('Usage: node cli.js <game-slug> <level-number>');
  console.error('Example: node cli.js steampunk-rune-chamber 2');
  process.exit(1);
}

const gameSlug = args[0];
const levelNumber = args[1];

if (!/^\d+$/.test(levelNumber)) {
  console.error(`Error: level-number must be an integer, got "${levelNumber}"`);
  process.exit(1);
}

const gameDir = resolve(repoRoot, 'games', gameSlug);

// If game doesn't exist, scaffold it
if (!existsSync(gameDir)) {
  console.log(`\n  Game "${gameSlug}" not found — scaffolding new game...\n`);
  scaffoldGame(gameDir, gameSlug);
}

const gamePath = resolve(repoRoot, 'games', gameSlug);

// Ensure src/levels directory exists (for new levels on existing games too)
const levelsDir = resolve(gamePath, 'src', 'levels');
if (!existsSync(levelsDir)) {
  mkdirSync(levelsDir, { recursive: true });
}

/**
 * Scaffold a minimal Immersio game directory so the editor can work with it.
 */
function scaffoldGame(dir, slug) {
  // Convert slug to title: "my-cool-game" → "My Cool Game"
  const title = slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  // Create directories
  const dirs = [
    '',
    'public',
    'public/models',
    'public/models/1',
    'src',
    'src/levels',
    'src/engine',
    'src/events',
    'src/assets',
    'src/levels',
  ];
  for (const d of dirs) {
    mkdirSync(resolve(dir, d), { recursive: true });
  }

  // package.json
  writeFileSync(resolve(dir, 'package.json'), JSON.stringify({
    name: slug,
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite --host 0.0.0.0',
      build: 'vite build',
      preview: 'vite preview --host 0.0.0.0',
    },
    dependencies: { three: '^0.170.0' },
    devDependencies: { '@vitejs/plugin-basic-ssl': '^1.1.0', vite: '^6.0.0' },
  }, null, 2) + '\n');

  // vite.config.js
  writeFileSync(resolve(dir, 'vite.config.js'),
`import { defineConfig } from 'vite';
import basicSsl from '@vitejs/plugin-basic-ssl';

export default defineConfig({
  plugins: [basicSsl()],
  server: {
    https: true,
    host: '0.0.0.0',
    port: 5173
  }
});
`);

  // index.html
  writeFileSync(resolve(dir, 'index.html'),
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #000; overflow: hidden; }
    canvas { display: block; }
  </style>
</head>
<body>
  <script type="module" src="/src/main.js"></script>
</body>
</html>
`);

  // src/main.js — minimal placeholder
  writeFileSync(resolve(dir, 'src', 'main.js'),
`// ${title} — Generated by Immersio Editor
// This game was scaffolded automatically. Build your levels in the editor!
console.log('${title} — use the Immersio editor to build levels');
`);

  // GAME_DESIGN.md
  writeFileSync(resolve(dir, 'GAME_DESIGN.md'),
`# ${title}

Created with the Immersio Level Editor.

## Levels

Levels are stored in \`src/levels/\` and can be edited with:
\`\`\`
npm run editor ${slug} <level-number>
\`\`\`
`);

  console.log(`  Created: games/${slug}/`);
  console.log(`    ├── package.json`);
  console.log(`    ├── vite.config.js`);
  console.log(`    ├── index.html`);
  console.log(`    ├── GAME_DESIGN.md`);
  console.log(`    ├── public/models/1/`);
  console.log(`    └── src/`);
  console.log(`        ├── main.js`);
  console.log(`        └── levels/`);
  console.log('');
}

console.log(`\nImmersio Level Editor`);
console.log(`  Game:  ${gameSlug}`);
console.log(`  Level: ${levelNumber}`);
console.log(`  Path:  ${gamePath}\n`);

const vite = spawn('npx', ['vite', '--open'], {
  cwd: __dirname,
  stdio: 'inherit',
  env: {
    ...process.env,
    VITE_GAME_SLUG: gameSlug,
    VITE_GAME_PATH: gamePath,
    VITE_LEVEL_NUMBER: levelNumber,
  },
});

vite.on('error', (err) => {
  console.error('Failed to start Vite:', err.message);
  process.exit(1);
});

vite.on('close', (code) => {
  process.exit(code ?? 0);
});
